# Generated by Django 3.1.7 on 2021-04-20 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=150)),
                ('modelo', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
            ],
        ),
    ]
