# Generated by Django 3.1.7 on 2021-04-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0002_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandReference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=150)),
                ('brand_id', models.IntegerField()),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('delete_at', models.DateTimeField()),
            ],
        ),
    ]
