# Generated by Django 3.1.7 on 2021-04-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0003_brandreference'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='marca',
        ),
        migrations.AddField(
            model_name='auto',
            name='brand_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auto',
            name='cilindraje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auto',
            name='clase',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='auto',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='delate_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='auto',
            name='kilometraje',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auto',
            name='numero_chasis',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='auto',
            name='numero_motor',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='auto',
            name='placa',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='auto',
            name='reference_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='auto',
            name='tipo',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='auto',
            name='tipo_combustible',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='auto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='color',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='auto',
            name='modelo',
            field=models.IntegerField(default=0),
        ),
    ]
