# Generated by Django 3.1.7 on 2021-04-28 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0006_auto_20210421_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auto',
            name='delate_at',
        ),
        migrations.AddField(
            model_name='auto',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='auto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
