# Generated by Django 3.1.7 on 2021-04-28 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0007_auto_20210428_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
