# Generated by Django 3.1.7 on 2021-05-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0008_auto_20210428_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandreference',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='brandreference',
            name='delete_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='brandreference',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
