# Generated by Django 3.1.7 on 2021-04-21 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0004_auto_20210421_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandreference',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.brand'),
        ),
    ]
