# Generated by Django 3.1.7 on 2021-04-21 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automobile', '0005_auto_20210421_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auto',
            name='brand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.brand'),
        ),
        migrations.AlterField(
            model_name='auto',
            name='reference_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automobile.brandreference'),
        ),
    ]
